// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8bgMQ8MF64-G3dWACdWcxswTG_uH5XuM',
    appId: '1:710899897768:web:297fc955a7da536468b99d',
    messagingSenderId: '710899897768',
    projectId: 'receipt-maker-398a8',
    authDomain: 'receipt-maker-398a8.firebaseapp.com',
    storageBucket: 'receipt-maker-398a8.firebasestorage.app',
    measurementId: 'G-WZW7KQ9QG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFU_FCvUxuw85gOamQBwdyI_DhtIhxnEk',
    appId: '1:710899897768:android:a3ebb97dd2530fe768b99d',
    messagingSenderId: '710899897768',
    projectId: 'receipt-maker-398a8',
    storageBucket: 'receipt-maker-398a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-AFY_5L4VF3XFHnPaXBIgaGBdJpM1f1Y',
    appId: '1:710899897768:ios:43f775ac8496944d68b99d',
    messagingSenderId: '710899897768',
    projectId: 'receipt-maker-398a8',
    storageBucket: 'receipt-maker-398a8.firebasestorage.app',
    androidClientId: '710899897768-q4uk2bv3otp464p5vtqhp5845a220ud5.apps.googleusercontent.com',
    iosClientId: '710899897768-ejumt1k220mvlok6n015j3866na4q0pk.apps.googleusercontent.com',
    iosBundleId: 'com.pixelperfect.receipt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-AFY_5L4VF3XFHnPaXBIgaGBdJpM1f1Y',
    appId: '1:710899897768:ios:24f1a3a78babf72a68b99d',
    messagingSenderId: '710899897768',
    projectId: 'receipt-maker-398a8',
    storageBucket: 'receipt-maker-398a8.firebasestorage.app',
    androidClientId: '710899897768-q4uk2bv3otp464p5vtqhp5845a220ud5.apps.googleusercontent.com',
    iosClientId: '710899897768-t2h22vtiaoqp74b3jhp0unf7o220l85m.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoPracGetx',
  );

}