// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTWh86tWbhygufUosvn7OGwYdrMycCPzA',
    appId: '1:134369591951:web:5cf271caa468b073d8a6fa',
    messagingSenderId: '134369591951',
    projectId: 'getyourinvoice-8f128',
    authDomain: 'getyourinvoice-8f128.firebaseapp.com',
    storageBucket: 'getyourinvoice-8f128.firebasestorage.app',
    measurementId: 'G-CSDLF9TJ6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU6Pp4h8ulxUhVn-DTyCZt9b-eOMeb6p4',
    appId: '1:134369591951:android:156b53ff86bb97dcd8a6fa',
    messagingSenderId: '134369591951',
    projectId: 'getyourinvoice-8f128',
    storageBucket: 'getyourinvoice-8f128.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4HE8NPhFb3QG3yJSrFNZWE0xfkyHBbZ4',
    appId: '1:134369591951:ios:85b0ef501be1f4c3d8a6fa',
    messagingSenderId: '134369591951',
    projectId: 'getyourinvoice-8f128',
    storageBucket: 'getyourinvoice-8f128.firebasestorage.app',
    iosBundleId: 'com.example.GetYourInvoice',
  );
}
